In [97]:
#Learning material from https://learn.365datascience.com/courses/data-cleaning-preprocessing-pandas
# pandas official documentation : https://pandas.pydata.org/docs/
#Tis is part 1 : Basis - Series
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'1.5.1'

In [4]:
products=['A','B','C','D']
products

['A', 'B', 'C', 'D']

In [5]:
type(products)

list

In [6]:
#creating series from python list
product_categories = pd.Series(products)

In [7]:
product_categories

0    A
1    B
2    C
3    D
dtype: object

In [18]:
product_categories.dtype
#'O' refers to object which is the default type assigned to non-numeric data

dtype('O')

In [19]:
product_categories.size

4

In [20]:
type(product_categories)
type(pd.Series(products))

pandas.core.series.Series

In [21]:
product_categories.name

In [23]:
print(product_categories.name)
#product_ctegories is the name used to refer the obj in the code
#object name - is the name you want to see when you display the contents

None


In [26]:
product_categories.name = "Product Categories"
product_categories

0    A
1    B
2    C
3    D
Name: Product Categories, dtype: object

In [9]:
daily_rate_dollars=([40,45,50,60])
daily_rate_dollars

[40, 45, 50, 60]

In [15]:
print(daily_rate_dollars)
type(daily_rate_dollars)

[40, 45, 50, 60]


list

In [11]:
import numpy as np

In [12]:
array_a=np.array([10,20,30,40,40,60])
array_a

array([10, 20, 30, 40, 40, 60])

In [13]:
type(array_a)

numpy.ndarray

In [14]:
#creating series from numpy array
series_a= pd.Series(array_a)
series_a

0    10
1    20
2    30
3    40
4    40
5    60
dtype: int32

In [27]:
prices_per_category= {'Product A':22250,'Product B':16600,'Product C':15600}
prices_per_category

{'Product A': 22250, 'Product B': 16600, 'Product C': 15600}

In [28]:
type(prices_per_category)

dict

In [29]:
#creating series from python dictionary
#override the variable
prices_per_category = pd.Series(prices_per_category)
# creating series from a dictionary preserves the Key value relationship 
#by translating keys into indexes(access labels) in Series
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [30]:
type(prices_per_category)

pandas.core.series.Series

In [31]:
#Series index is a separate object
prices_per_category.index

Index(['Product A', 'Product B', 'Product C'], dtype='object')

In [35]:
#types of Indexes
type(series_a.index)


pandas.core.indexes.range.RangeIndex

In [36]:
type(prices_per_category.index)

pandas.core.indexes.base.Index

In [37]:
series_a.index

RangeIndex(start=0, stop=6, step=1)

In [38]:
prices_per_category.index

Index(['Product A', 'Product B', 'Product C'], dtype='object')

In [39]:
# Label index (explicit indexing) also has the default indexes (implicit indexing) associated with it
prices_per_category['Product A']

22250

In [40]:
prices_per_category[0]

22250

In [43]:
#Intergers as explicit indexing 
#Avoid: Explicitly naming index as integers
series_b = pd.Series([10,20,30,40,50],index=[1,2,3,4,5])
series_b

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [45]:
series_b[0]

KeyError: 0

In [46]:
series_b[1]

10

In [49]:
#Avoid: Input Integers as String
series_c = pd.Series([11,22,33,44,55],index=["1","2","3","4","5"])
series_c

1    11
2    22
3    33
4    44
5    55
dtype: int64

In [50]:
series_c[1]

22

In [51]:
series_c["1"]

11

In [53]:
start_date_deposites = pd.Series({
    '7/4/2014' :2000,
    '1/2/2014' :2000,  
    '12/8/2014' :1000,
    '2/20/2014' :2000,
    '10/28/2014' :2000, 
    '4/19/2014' :2000,
    '7/4/2014' :2000,
    '4/24/2014' :2000,
    '9/3/2014' :4000,
    '7/25/2014' :2000,
    '5/1/2014' :2000,
    '3/29/2014' :2000,
    '10/3/2014' :2000,
    '9/18/2014' :2500,
})

start_date_deposites

7/4/2014      2000
1/2/2014      2000
12/8/2014     1000
2/20/2014     2000
10/28/2014    2000
4/19/2014     2000
4/24/2014     2000
9/3/2014      4000
7/25/2014     2000
5/1/2014      2000
3/29/2014     2000
10/3/2014     2000
9/18/2014     2500
dtype: int64

In [54]:
start_date_deposites.sum()

27500

In [63]:
start_date_deposites.min()

1000

In [56]:
start_date_deposites.max()

4000

In [62]:
start_date_deposites.idxmin()

'12/8/2014'

In [64]:
#head method provides efficient way to catch a glimpse of the structure of data set
#start_date_deposites.head(3)
#start_date_deposites.head(n=5)

start_date_deposites.head()


7/4/2014      2000
1/2/2014      2000
12/8/2014     1000
2/20/2014     2000
10/28/2014    2000
dtype: int64

In [65]:
data = pd.read_csv('Location.csv').squeeze()
location_data = data.copy()
location_data.head()

0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [66]:
#count: total rows, unique:total uniques rows, top: most repeated values, 
location_data.describe()

count            1043
unique            296
top       Location 25
freq               31
Name: Location, dtype: object

In [67]:
#number of unique rows, can also use location_data.size()
location_data.nunique()

296

In [68]:
# returns array of all unique values, displays the values in the order they apper in teh data
location_data.unique()

array(['Location 3', 'Location 6', 'Location 8', 'Location 26',
       'Location 34', 'Location 25', 'Location 46', 'Location 156',
       'Location 21', 'Location 13', 'Location 579', 'Location 602',
       'Location 10', 'Location 44', 'Location 30', 'Location 48',
       'Location 196', 'Location 64', 'Location 91', 'Location 62',
       'Location 75', 'Location 42', 'Location 233', 'Location 95',
       'Location 78', 'Location 61', 'Location 87', 'Location 19',
       'Location 115', 'Location 350', 'Location 377', 'Location 17',
       'Location 113', 'Location 81', 'Location 58', 'Location 212',
       'Location 53', 'Location 337', 'Location 41', 'Location 632',
       'Location 73', 'Location 214', 'Location 218', 'Location 38',
       'Location 172', 'Location 197', 'Location 101', 'Location 185',
       'Location 129', 'Location 235', 'Location 142', 'Location 50',
       'Location 76', 'Location 11', 'Location 33', 'Location 22',
       'Location 145', 'Location 203', 'Loca

In [79]:
#Converting series into array: pandas.array will be used when your work is exclusively centered around 
#functionalities of pandas library

#. value, .array, .to_numpy all will convert series to an array. 
#.value will be out of use in the coming version of pandas


prices_per_category.array

<PandasArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [80]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.PandasArray

In [81]:
#to create a direct relation bet seies values and numpy array use .to_numpy()
#this allows you to proceed with math and stat computations of further preprocession of data 
prices_per_category.to_numpy()

array([22250, 16600, 15600], dtype=int64)

In [82]:
type(prices_per_category.to_numpy())

numpy.ndarray

In [83]:
##====SORTING====##
numbers=pd.Series([15,1000,23,45,444])
numbers

0      15
1    1000
2      23
3      45
4     444
dtype: int64

In [85]:
##default sorting is asc
numbers.sort_values()

0      15
2      23
3      45
4     444
1    1000
dtype: int64

In [86]:
numbers.sort_values(ascending=False)

1    1000
4     444
3      45
2      23
0      15
dtype: int64

In [87]:
#sort_value() arranges the values of the object its been applied
# index values will comply with object's data

location_data.sort_values()

637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [88]:
#Attribute Chaining and Method chaining
#1. Attribute Chaining
location_data.name

'Location'

In [89]:
location_data.index

RangeIndex(start=0, stop=1043, step=1)

In [90]:
#to get the name of an index and not name of the Series we use chaining
location_data.index.name

In [91]:
location_data.index.name = 'Index'
location_data.index.name

'Index'

In [93]:
#2.Method Chaining
location_data.sort_values(ascending= False).head(6)

Index
372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
669    Location 97
Name: Location, dtype: object

In [94]:
location_data.index.to_numpy()

array([   0,    1,    2, ..., 1040, 1041, 1042], dtype=int64)

In [96]:
## ADVANTAGES of chaining
# We are not required to 1.store Intermediate output or 2.intermediately returned values
#Saving the time to create a variable 

In [99]:
location_data_sv=location_data.sort_values(ascending=False)
location_data_sv

Index
372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
          ...     
202    Location 10
298    Location 10
637     Location 1
884     Location 1
465     Location 1
Name: Location, Length: 1043, dtype: object

In [100]:
location_data_sv.index

Int64Index([ 372,  757,  128,  482,  271,  669,  612,   29,  518,  598,
            ...
             904,  912, 1010,   14,  716,  202,  298,  637,  884,  465],
           dtype='int64', name='Index', length=1043)

In [101]:
location_data_sv.index.sort_values()

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042],
           dtype='int64', name='Index', length=1043)

In [103]:
#Chain index() and Sort() will only sort indexex col and the values corresonding to indexex are not rearranged as per index.
# Key value pair is disturbed

location_data_sv.index=location_data_sv.index.sort_values()
location_data_sv

Index
0       Location 99
1       Location 98
2       Location 97
3       Location 97
4       Location 97
           ...     
1038    Location 10
1039    Location 10
1040     Location 1
1041     Location 1
1042     Location 1
Name: Location, Length: 1043, dtype: object

In [105]:
# Hence we use sort_index() instead of chaining

location_data_sv=location_data.sort_values(ascending=False)
location_data_sv
location_data_sv.sort_index()

Index
0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object